Repository Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit, pull requests merged in 2020-12, with the labels that each got.

#55 [INFRA] Reduce size of TFLEARN models for brain extraction
  notebooks/optimize_tensorflow_checkpoint.ipynb
  pymialsrtk/interfaces/preprocess.py
Labels: maintenance, mid-effort

#61 [ENH] Add script that wraps the call to Singularity image
  pymialsrtk/cli/mialsuperresolutiontoolkit_bidsapp_docker.py
  pymialsrtk/cli/mialsuperresolutiontoolkit_bidsapp_singularity.py
  setup.py
  setup_pypi.py
Labels: enhancement

#60 [ENH] Creation of singularity image during continuous integration
  .circleci/config.yml
  .circleci/test-03_outputs.txt
  .circleci/test-04_outputs.txt
  docker/bidsapp/Dockerfile
  docker/bidsapp/entrypoints/run_srr.sh
  docker/bidsapp/entrypoints/run_srr_coverage.sh
Labels: enhancement

#65 [DOC] Update documentation
  .circleci/config.yml
  README.md
  documentation/api_commandlineinterface.rst
  documentation/api_pipelines.rst
  documentation/api_postprocess.rst
  documentation/api_preprocess.rst
  documentation/api_reconstruction.rst
  documentation/api_utils.rst
  documentation/conf.py
  documentation/index.rst
  documentation/installation.rst
  documentation/requirements.txt
  documentation/usage.rst
  pymialsrtk/cli/mialsuperresolutiontoolkit_docker.py
  pymialsrtk/cli/mialsuperresolutiontoolkit_singularity.py
  pymialsrtk/interfaces/postprocess.py
  pymialsrtk/interfaces/preprocess.py
  pymialsrtk/interfaces/reconstruction.py
  setup.py
  setup_pypi.py
Labels: documentation, maintenance, mid-effort

#63 [ENH] Add possibility for the user to custom the skipped interfaces
  .circleci/test-01_outputs.txt
  .circleci/test-02_outputs.txt
  .circleci/test-03_outputs.txt
  .circleci/test-04_outputs.txt
  data/code/participants_params.json
  docker/bidsapp/run.py
  documentation/usage.rst
  pymialsrtk/interfaces/postprocess.py
  pymialsrtk/interfaces/reconstruction.py
  pymialsrtk/pipelines/anatomical/srr.py
Labels: big-effort, enhancement
